import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createHash, generateKeyPairSync, randomBytes } from "node:crypto";

const SPAWN_TIMEOUT_MS = 15_000;

export type CloudInitOpts = {
  hostname?: string;
  timezone?: string;
  locale?: string;
  user: { username: string; password_hash: string; sudo_nopasswd?: boolean };
  ssh_pubkey?: string;
  // U1: renamed hidden → scan_ssid to match wpa_supplicant field name
  wifi?: { ssid: string; psk?: string; country: string; scan_ssid?: boolean };
  packages?: string[];
  runcmd?: string[];
};

function yamlEscapeDq(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function cloudInitYaml(p: CloudInitOpts): string {
  const lines: string[] = ["#cloud-config"];
  if (p.hostname) lines.push(`hostname: ${p.hostname}`);
  if (p.timezone) lines.push(`timezone: ${p.timezone}`);
  if (p.locale) lines.push(`locale: ${p.locale}`);
  lines.push("users:");
  lines.push(`  - name: ${p.user.username}`);
  // S9: sudo_nopasswd defaults to false; only emit when explicitly true
  if (p.user.sudo_nopasswd === true) lines.push(`    sudo: ALL=(ALL) NOPASSWD:ALL`);
  lines.push(`    groups: users,adm,dialout,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render`);
  lines.push(`    shell: /bin/bash`);
  // S10: only password_hash. plain_text_passwd is never emitted.
  if (!p.user.password_hash) {
    throw new Error("cloud-init user requires password_hash (refusing to emit plain_text_passwd)");
  }
  lines.push(`    lock_passwd: false`);
  lines.push(`    passwd: "${yamlEscapeDq(p.user.password_hash)}"`);
  if (p.ssh_pubkey) {
    lines.push(`    ssh_authorized_keys:`);
    lines.push(`      - "${yamlEscapeDq(p.ssh_pubkey)}"`);
  }
  if (p.packages?.length) {
    lines.push("package_update: true");
    lines.push("packages:");
    // S2: quote so package names containing YAML-special chars can't escape the list item
    for (const pk of p.packages) lines.push(`  - "${yamlEscapeDq(pk)}"`);
  }
  if (p.wifi) {
    lines.push("write_files:");
    lines.push("  - path: /etc/netplan/50-cloud-init.yaml");
    lines.push("    permissions: '0600'");
    lines.push("    content: |");
    lines.push("      network:");
    lines.push("        version: 2");
    lines.push("        wifis:");
    lines.push("          wlan0:");
    lines.push("            dhcp4: true");
    lines.push("            optional: true");
    // B1: emit regulatory-domain for the country
    lines.push(`            regulatory-domain: ${p.wifi.country.toUpperCase()}`);
    lines.push("            access-points:");
    lines.push(`              "${yamlEscapeDq(p.wifi.ssid)}":`);
    if (p.wifi.psk) lines.push(`                password: "${yamlEscapeDq(p.wifi.psk)}"`);
    // U1: scan_ssid → netplan's `hidden: true` (same semantics, unified field name)
    if (p.wifi.scan_ssid) lines.push(`                hidden: true`);
  }
  if (p.runcmd?.length) {
    lines.push("runcmd:");
    // S1: quote each command so YAML-meaningful chars (`:`, `#`, `[` ...) can't break parsing
    for (const c of p.runcmd) lines.push(`  - "${yamlEscapeDq(c)}"`);
  }
  return lines.join("\n") + "\n";
}

export type DietPiOpts = {
  password_hash?: string;
  hostname?: string;
  timezone?: string;
  locale?: string;
  keyboard_layout?: string;
  headless?: boolean;
  ssh_server?: boolean;
  autostart?: string;
  wifi?: { ssid: string; psk?: string; key_mgmt?: "WPA-PSK" | "NONE"; country: string };
};

export function dietpiTxt(p: DietPiOpts): string {
  // S4: refuse to emit without an explicit password_hash. No "dietpi" default.
  if (!p.password_hash) {
    throw new Error("dietpi_config requires 'dietpi.password' or 'dietpi.password_hash' (refusing to emit hardcoded default)");
  }
  // B2: require explicit country when wifi is configured
  if (p.wifi && !p.wifi.country) {
    throw new Error("dietpi_config wifi requires explicit 'country' (regulatory code, ISO 3166-1 alpha-2)");
  }
  const lines: string[] = [
    "# dietpi.txt — generated by raspberry-pi-setup-mcp",
    "#------------------------------------------------",
    // S4: single-quote values so shell metacharacters can't escape assignment
    `AUTO_SETUP_LOCALE='${p.locale ?? "en_GB.UTF-8"}'`,
    `AUTO_SETUP_KEYBOARD_LAYOUT='${p.keyboard_layout ?? "us"}'`,
    `AUTO_SETUP_TIMEZONE='${p.timezone ?? "UTC"}'`,
    `AUTO_SETUP_NET_WIFI_ENABLED=${p.wifi ? 1 : 0}`,
  ];
  if (p.wifi) {
    lines.push(`AUTO_SETUP_NET_WIFI_COUNTRY_CODE=${p.wifi.country.toUpperCase()}`);
  }
  lines.push(`AUTO_SETUP_NET_HOSTNAME='${p.hostname ?? "DietPi"}'`);
  lines.push(`AUTO_SETUP_HEADLESS=${p.headless === false ? 0 : 1}`);
  // B3: per current dietpi.txt docs, OpenSSH server index is -3, Dropbear is -2.
  // Use OpenSSH (-3) as the enabled default; -1 disables.
  lines.push(`AUTO_SETUP_SSH_SERVER_INDEX=${p.ssh_server === false ? -1 : -3}`);
  lines.push(`AUTO_SETUP_GLOBAL_PASSWORD_HASH='${p.password_hash}'`);
  if (p.autostart) lines.push(`AUTO_SETUP_AUTOSTART_TARGET_INDEX='${p.autostart}'`);
  lines.push("SURVEY_OPTED_IN=0");
  return lines.join("\n") + "\n";
}

export function dietpiWifiTxt(p: { ssid: string; psk?: string; key_mgmt?: "WPA-PSK" | "NONE" }): string {
  // B4: empty SSID throws
  if (!p.ssid || p.ssid.length === 0) {
    throw new Error("dietpi-wifi.txt requires a non-empty ssid");
  }
  const km = p.key_mgmt ?? (p.psk ? "WPA-PSK" : "NONE");
  return [
    "# dietpi-wifi.txt — generated by raspberry-pi-setup-mcp",
    `aWIFI_SSID[0]='${p.ssid.replace(/'/g, "'\\''")}'`,
    `aWIFI_KEY[0]='${(p.psk ?? "").replace(/'/g, "'\\''")}'`,
    `aWIFI_KEYMGR[0]='${km}'`,
    "",
  ].join("\n");
}

type WinDisk = {
  Number?: number;
  FriendlyName?: string;
  Size?: number;
  BusType?: string;
  PartitionStyle?: string;
  IsOffline?: boolean;
};

type LinuxBlockDevice = {
  name: string;
  size?: string;
  type?: string;
  // B8: util-linux >= 2.37 reports `mountpoints` (array) instead of singular `mountpoint`.
  mountpoint?: string | null;
  mountpoints?: (string | null)[];
  rm?: boolean;
  rota?: boolean;
  tran?: string;
  model?: string;
  children?: LinuxBlockDevice[];
};

export type ListBlockDevicesResult =
  | { ok: true; platform: "win32"; devices: Array<{
      index?: number;
      name?: string;
      size?: number;
      size_gb: number | null;
      bus?: string;
      partition_style?: string;
      offline?: boolean;
      is_removable: boolean;
    }> }
  | { ok: true; platform: "darwin"; raw_plist: string }
  | { ok: true; platform: "linux"; devices: LinuxBlockDevice[] }
  | { ok: false; platform: string; error: string };

function stripBom(s: string): string {
  if (s.charCodeAt(0) === 0xfeff) return s.slice(1);
  return s;
}

export function listBlockDevices(): ListBlockDevicesResult {
  if (process.platform === "win32") {
    // B12: force UTF-8 stdout encoding so Get-Disk JSON parses cleanly.
    const psScript =
      "[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new(); " +
      "Get-Disk | Select-Object Number,FriendlyName,Size,BusType,PartitionStyle,IsOffline | ConvertTo-Json -Depth 3";
    const r = spawnSync("powershell", ["-NoProfile", "-Command", psScript], {
      encoding: "utf8",
      timeout: SPAWN_TIMEOUT_MS,
      killSignal: "SIGTERM",
    });
    if (r.error || r.status !== 0) {
      return { ok: false, platform: "win32", error: r.error?.message || r.stderr || "powershell failed" };
    }
    let parsed: unknown;
    const stdout = stripBom(r.stdout);
    try {
      parsed = JSON.parse(stdout);
    } catch (e) {
      // B13: surface structured error rather than wrapping raw stdout
      return {
        ok: false,
        platform: "win32",
        error: `failed to parse Get-Disk JSON: ${(e as Error).message}`,
      };
    }
    const arr: WinDisk[] = Array.isArray(parsed)
      ? (parsed as WinDisk[])
      : parsed
      ? [parsed as WinDisk]
      : [];
    return {
      ok: true,
      platform: "win32",
      devices: arr.map((d) => ({
        index: d.Number,
        name: d.FriendlyName,
        size: d.Size,
        size_gb: d.Size ? Math.round((d.Size / 1e9) * 10) / 10 : null,
        bus: d.BusType,
        partition_style: d.PartitionStyle,
        offline: d.IsOffline,
        is_removable:
          String(d.BusType).toUpperCase().includes("USB") ||
          String(d.BusType).toUpperCase().includes("SD"),
      })),
    };
  }
  if (process.platform === "darwin") {
    const r = spawnSync("diskutil", ["list", "-plist", "external"], {
      encoding: "utf8",
      timeout: SPAWN_TIMEOUT_MS,
      killSignal: "SIGTERM",
    });
    if (r.status !== 0) return { ok: false, platform: "darwin", error: r.stderr || "diskutil failed" };
    return { ok: true, platform: "darwin", raw_plist: r.stdout };
  }
  if (process.platform === "linux") {
    // C2: util-linux >=2.37 emits `mountpoints` (array) instead of singular `mountpoint`.
    // Include MOUNTPOINTS in the -o list; the LinuxBlockDevice type accepts both.
    const r = spawnSync(
      "lsblk",
      ["-J", "-o", "NAME,SIZE,TYPE,MOUNTPOINTS,RM,ROTA,TRAN,MODEL"],
      { encoding: "utf8", timeout: SPAWN_TIMEOUT_MS, killSignal: "SIGTERM" },
    );
    if (r.status !== 0) return { ok: false, platform: "linux", error: r.stderr || "lsblk failed" };
    try {
      const parsed = JSON.parse(r.stdout) as { blockdevices: LinuxBlockDevice[] };
      return { ok: true, platform: "linux", devices: parsed.blockdevices };
    } catch (e) {
      // B9: include lsblk's stderr (if any) in the diagnostic.
      const stderrSnippet = r.stderr?.trim();
      const detail = stderrSnippet
        ? `${(e as Error).message} (lsblk stderr: ${stderrSnippet})`
        : (e as Error).message;
      return { ok: false, platform: "linux", error: `failed to parse lsblk JSON: ${detail}` };
    }
  }
  return { ok: false, platform: process.platform, error: "unsupported platform" };
}

// ---------------------------------------------------------------------------
// SSH keypair generation — pure Node crypto, no shell-out (S5/S6/B9/B10)
// ---------------------------------------------------------------------------

const OPENSSH_MAGIC = Buffer.from("openssh-key-v1\0", "utf8");

function writeUint32BE(n: number): Buffer {
  const b = Buffer.alloc(4);
  b.writeUInt32BE(n >>> 0, 0);
  return b;
}

function writeString(buf: Buffer): Buffer {
  return Buffer.concat([writeUint32BE(buf.length), buf]);
}

function ed25519PublicKeyBlob(rawPub: Buffer): Buffer {
  return Buffer.concat([
    writeString(Buffer.from("ssh-ed25519")),
    writeString(rawPub),
  ]);
}

function ed25519AuthorizedKey(rawPub: Buffer, comment: string): string {
  const blob = ed25519PublicKeyBlob(rawPub);
  return `ssh-ed25519 ${blob.toString("base64")}${comment ? " " + comment : ""}\n`;
}

function fingerprintSha256(rawPub: Buffer, keyType: "ssh-ed25519"): string {
  // B7: keyType is statically "ssh-ed25519"; no else branch needed.
  if (keyType !== "ssh-ed25519") {
    throw new Error(`unsupported keyType for fingerprintSha256: ${keyType as string}`);
  }
  const blob = ed25519PublicKeyBlob(rawPub);
  const digest = createHash("sha256").update(blob).digest("base64");
  // OpenSSH strips trailing '=' padding from SHA256 fingerprints
  return `SHA256:${digest.replace(/=+$/, "")}`;
}

// id-Ed25519 OID = 1.3.101.112 → DER OID body `2B 65 70`.
// B4: verify the structural prefix instead of trusting length alone, so a future
// node:crypto change in encoding fails loudly instead of silently emitting a corrupt key.
const ED25519_OID = Buffer.from([0x2b, 0x65, 0x70]);

function rawEd25519PublicFromSpki(spkiDer: Buffer): Buffer {
  // Expected: 30 2A 30 05 06 03 2B 65 70 03 21 00 <32 bytes raw pub>
  if (spkiDer.length !== 44) {
    throw new Error(`unexpected ed25519 SPKI length: ${spkiDer.length}`);
  }
  if (spkiDer[0] !== 0x30 || spkiDer[1] !== 0x2a) {
    throw new Error("ed25519 SPKI: outer SEQUENCE header mismatch");
  }
  if (spkiDer[2] !== 0x30 || spkiDer[3] !== 0x05) {
    throw new Error("ed25519 SPKI: AlgorithmIdentifier SEQUENCE header mismatch");
  }
  if (spkiDer[4] !== 0x06 || spkiDer[5] !== 0x03 || !spkiDer.subarray(6, 9).equals(ED25519_OID)) {
    throw new Error("ed25519 SPKI: id-Ed25519 OID mismatch");
  }
  if (spkiDer[9] !== 0x03 || spkiDer[10] !== 0x21 || spkiDer[11] !== 0x00) {
    throw new Error("ed25519 SPKI: BIT STRING header mismatch");
  }
  return spkiDer.subarray(12);
}

function rawEd25519PrivateFromPkcs8(pkcs8Der: Buffer): Buffer {
  // Expected: 30 2E 02 01 00 30 05 06 03 2B 65 70 04 22 04 20 <32 bytes raw seed>
  if (pkcs8Der.length !== 48) {
    throw new Error(`unexpected ed25519 PKCS8 length: ${pkcs8Der.length}`);
  }
  if (pkcs8Der[0] !== 0x30 || pkcs8Der[1] !== 0x2e) {
    throw new Error("ed25519 PKCS8: outer SEQUENCE header mismatch");
  }
  if (pkcs8Der[2] !== 0x02 || pkcs8Der[3] !== 0x01 || pkcs8Der[4] !== 0x00) {
    throw new Error("ed25519 PKCS8: version INTEGER header mismatch");
  }
  if (pkcs8Der[5] !== 0x30 || pkcs8Der[6] !== 0x05) {
    throw new Error("ed25519 PKCS8: AlgorithmIdentifier SEQUENCE header mismatch");
  }
  if (pkcs8Der[7] !== 0x06 || pkcs8Der[8] !== 0x03 || !pkcs8Der.subarray(9, 12).equals(ED25519_OID)) {
    throw new Error("ed25519 PKCS8: id-Ed25519 OID mismatch");
  }
  // Outer OCTET STRING wrapping the inner OCTET STRING (CurvePrivateKey).
  if (pkcs8Der[12] !== 0x04 || pkcs8Der[13] !== 0x22) {
    throw new Error("ed25519 PKCS8: outer OCTET STRING header mismatch");
  }
  if (pkcs8Der[14] !== 0x04 || pkcs8Der[15] !== 0x20) {
    throw new Error("ed25519 PKCS8: inner OCTET STRING header mismatch");
  }
  return pkcs8Der.subarray(16);
}

function buildOpenSshPrivateKey(rawPub: Buffer, rawPriv: Buffer, comment: string): string {
  // Unencrypted OpenSSH private key format for ed25519.
  const pub = ed25519PublicKeyBlob(rawPub);
  // S5: OpenSSH spec says checkint should be unpredictable; use a CSPRNG.
  const checkint = randomBytes(4).readUInt32BE(0);
  const privSection = Buffer.concat([
    writeUint32BE(checkint),
    writeUint32BE(checkint),
    writeString(Buffer.from("ssh-ed25519")),
    writeString(rawPub),
    writeString(Buffer.concat([rawPriv, rawPub])), // 64-byte private = seed || pub
    writeString(Buffer.from(comment)),
  ]);
  // pad to 8-byte block
  const padLen = (8 - (privSection.length % 8)) % 8;
  const pad = Buffer.alloc(padLen);
  for (let i = 0; i < padLen; i++) pad[i] = i + 1;
  const padded = Buffer.concat([privSection, pad]);

  const blob = Buffer.concat([
    OPENSSH_MAGIC,
    writeString(Buffer.from("none")), // ciphername
    writeString(Buffer.from("none")), // kdfname
    writeString(Buffer.alloc(0)),     // kdfoptions
    writeUint32BE(1),                 // num keys
    writeString(pub),
    writeString(padded),
  ]);

  const b64 = blob.toString("base64");
  // B6: match() can return null on empty input — fall back to [].
  const wrapped = (b64.match(/.{1,70}/g) ?? []).join("\n");
  return `-----BEGIN OPENSSH PRIVATE KEY-----\n${wrapped}\n-----END OPENSSH PRIVATE KEY-----\n`;
}

export function generateSshKeypair(p: {
  comment?: string;
  passphrase?: string; // ignored — pure-Node OpenSSH key writer below does not encrypt
  type?: "ed25519" | "rsa" | "ecdsa";
  bits?: number;
  private_key_path: string;
}): {
  publicKey: string;
  fingerprint: string;
  privateKeyPath: string;
  pubKeyPath: string;
  type: string;
  mode_protected: boolean;
  warning?: string;
} {
  // S6/B9/B10: ed25519 only via node:crypto. RSA / ECDSA would need a more involved
  // OpenSSH key serializer; reject loudly so we don't leak via shell.
  const type = p.type ?? "ed25519";
  if (type !== "ed25519") {
    throw new Error(
      `ssh keypair type '${type}' not supported by the in-process generator. Use ed25519 or generate manually.`,
    );
  }
  // U4: ed25519 is fixed-length; bits parameter is meaningless and misleading
  if (p.bits !== undefined) {
    throw new Error("ssh_key_bits is not applicable for ed25519 (fixed-length key); omit the parameter.");
  }
  if (p.passphrase) {
    throw new Error("passphrase-protected key generation is not supported in-process; generate manually with ssh-keygen for that.");
  }
  if (!p.private_key_path) {
    throw new Error("generate_ssh_keypair requires 'private_key_path' (target file path)");
  }
  const targetPath = resolve(p.private_key_path);
  const comment = p.comment ?? `rpi-${Date.now()}`;
  if (/[\n\r"'`$\\]/.test(comment)) {
    throw new Error("ssh_key_comment must not contain newline, quote, backslash, or shell metacharacters");
  }

  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  const pkcs8 = privateKey.export({ format: "der", type: "pkcs8" }) as Buffer;
  const spki = publicKey.export({ format: "der", type: "spki" }) as Buffer;
  const rawPriv = rawEd25519PrivateFromPkcs8(pkcs8);
  const rawPub = rawEd25519PublicFromSpki(spki);

  const opensshPriv = buildOpenSshPrivateKey(rawPub, rawPriv, comment);
  const authorizedKey = ed25519AuthorizedKey(rawPub, comment);

  // S5: write private key with mode 0600 and DO NOT return it.
  // B5: writeFileSync({mode: 0o600}) is sufficient on POSIX. On Windows the mode is
  // ignored and the file inherits the parent ACL — surface this as a warning instead
  // of pretending chmodSync did anything useful.
  writeFileSync(targetPath, opensshPriv, { encoding: "utf8", mode: 0o600 });
  const pubPath = `${targetPath}.pub`;
  writeFileSync(pubPath, authorizedKey, { encoding: "utf8", mode: 0o644 });

  const isWin = process.platform === "win32";
  return {
    publicKey: authorizedKey.trim(),
    fingerprint: fingerprintSha256(rawPub, "ssh-ed25519"),
    privateKeyPath: targetPath,
    pubKeyPath: pubPath, // U3
    type,
    mode_protected: !isWin,
    ...(isWin
      ? {
          warning:
            "Windows: file mode 0600 is not enforced; the private key inherits the parent directory's ACL. Use a per-user .ssh directory under %USERPROFILE% or restrict ACLs manually with icacls if needed.",
        }
      : {}),
  };
}
