import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

export type CloudInitOpts = {
  hostname?: string;
  timezone?: string;
  locale?: string;
  user: { username: string; password?: string; password_hash?: string; sudo_nopasswd?: boolean };
  ssh_pubkey?: string;
  wifi?: { ssid: string; psk?: string; country: string; hidden?: boolean };
  packages?: string[];
  runcmd?: string[];
};

function yamlEscapeDq(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function cloudInitYaml(p: CloudInitOpts): string {
  const lines: string[] = ["#cloud-config"];
  if (p.hostname) lines.push(`hostname: ${p.hostname}`);
  if (p.timezone) lines.push(`timezone: ${p.timezone}`);
  if (p.locale) lines.push(`locale: ${p.locale}`);
  lines.push("users:");
  lines.push(`  - name: ${p.user.username}`);
  if (p.user.sudo_nopasswd !== false) lines.push(`    sudo: ALL=(ALL) NOPASSWD:ALL`);
  lines.push(`    groups: users,adm,dialout,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render`);
  lines.push(`    shell: /bin/bash`);
  if (p.user.password_hash) {
    lines.push(`    lock_passwd: false`);
    lines.push(`    passwd: "${yamlEscapeDq(p.user.password_hash)}"`);
  } else if (p.user.password) {
    lines.push(`    lock_passwd: false`);
    lines.push(`    plain_text_passwd: "${yamlEscapeDq(p.user.password)}"`);
  }
  if (p.ssh_pubkey) {
    lines.push(`    ssh_authorized_keys:`);
    lines.push(`      - "${yamlEscapeDq(p.ssh_pubkey)}"`);
  }
  if (p.packages?.length) {
    lines.push("package_update: true");
    lines.push("packages:");
    for (const pk of p.packages) lines.push(`  - ${pk}`);
  }
  if (p.wifi) {
    lines.push("write_files:");
    lines.push("  - path: /etc/netplan/50-cloud-init.yaml");
    lines.push("    permissions: '0600'");
    lines.push("    content: |");
    lines.push("      network:");
    lines.push("        version: 2");
    lines.push("        wifis:");
    lines.push("          wlan0:");
    lines.push("            dhcp4: true");
    lines.push("            optional: true");
    lines.push("            access-points:");
    lines.push(`              "${yamlEscapeDq(p.wifi.ssid)}":`);
    if (p.wifi.psk) lines.push(`                password: "${yamlEscapeDq(p.wifi.psk)}"`);
    if (p.wifi.hidden) lines.push(`                hidden: true`);
  }
  if (p.runcmd?.length) {
    lines.push("runcmd:");
    for (const c of p.runcmd) lines.push(`  - ${c}`);
  }
  return lines.join("\n") + "\n";
}

export type DietPiOpts = {
  password?: string;
  hostname?: string;
  timezone?: string;
  locale?: string;
  keyboard_layout?: string;
  headless?: boolean;
  ssh_server?: boolean;
  autostart?: string;
  wifi?: { ssid: string; psk?: string; key_mgmt?: "WPA-PSK" | "NONE"; country: string };
};

export function dietpiTxt(p: DietPiOpts): string {
  const lines: string[] = [
    "# dietpi.txt — generated by raspberry-pi-setup-mcp",
    "#------------------------------------------------",
    `AUTO_SETUP_LOCALE=${p.locale ?? "en_GB.UTF-8"}`,
    `AUTO_SETUP_KEYBOARD_LAYOUT=${p.keyboard_layout ?? "us"}`,
    `AUTO_SETUP_TIMEZONE=${p.timezone ?? "UTC"}`,
    `AUTO_SETUP_NET_WIFI_ENABLED=${p.wifi ? 1 : 0}`,
    p.wifi ? `AUTO_SETUP_NET_WIFI_COUNTRY_CODE=${p.wifi.country.toUpperCase()}` : `AUTO_SETUP_NET_WIFI_COUNTRY_CODE=US`,
    `AUTO_SETUP_NET_HOSTNAME=${p.hostname ?? "DietPi"}`,
    `AUTO_SETUP_HEADLESS=${p.headless === false ? 0 : 1}`,
    `AUTO_SETUP_SSH_SERVER_INDEX=${p.ssh_server === false ? -1 : -2}`,
    `AUTO_SETUP_GLOBAL_PASSWORD=${p.password ?? "dietpi"}`,
  ];
  if (p.autostart) lines.push(`AUTO_SETUP_AUTOSTART_TARGET_INDEX=${p.autostart}`);
  lines.push("SURVEY_OPTED_IN=0");
  return lines.join("\n") + "\n";
}

export function dietpiWifiTxt(p: { ssid: string; psk?: string; key_mgmt?: "WPA-PSK" | "NONE" }): string {
  const km = p.key_mgmt ?? (p.psk ? "WPA-PSK" : "NONE");
  return [
    "# dietpi-wifi.txt — generated by raspberry-pi-setup-mcp",
    `aWIFI_SSID[0]='${(p.ssid ?? "").replace(/'/g, "'\\''")}'`,
    `aWIFI_KEY[0]='${(p.psk ?? "").replace(/'/g, "'\\''")}'`,
    `aWIFI_KEYMGR[0]='${km}'`,
    "",
  ].join("\n");
}

export function listBlockDevices(): any {
  if (process.platform === "win32") {
    const r = spawnSync("powershell", [
      "-NoProfile", "-Command",
      "Get-Disk | Select-Object Number,FriendlyName,Size,BusType,PartitionStyle,IsOffline | ConvertTo-Json -Depth 3",
    ], { encoding: "utf8" });
    if (r.status !== 0) {
      return { ok: false, platform: "win32", error: r.stderr || "powershell failed" };
    }
    let parsed: any;
    try { parsed = JSON.parse(r.stdout); } catch { parsed = r.stdout; }
    const arr = Array.isArray(parsed) ? parsed : (parsed ? [parsed] : []);
    return {
      ok: true,
      platform: "win32",
      devices: arr.map((d: any) => ({
        index: d.Number,
        name: d.FriendlyName,
        size: d.Size,
        size_gb: d.Size ? Math.round((d.Size / 1e9) * 10) / 10 : null,
        bus: d.BusType,
        partition_style: d.PartitionStyle,
        offline: d.IsOffline,
        is_removable: String(d.BusType).toUpperCase().includes("USB") || String(d.BusType).toUpperCase().includes("SD"),
      })),
    };
  }
  if (process.platform === "darwin") {
    const r = spawnSync("diskutil", ["list", "-plist", "external"], { encoding: "utf8" });
    if (r.status !== 0) return { ok: false, platform: "darwin", error: r.stderr || "diskutil failed" };
    return { ok: true, platform: "darwin", raw_plist: r.stdout };
  }
  if (process.platform === "linux") {
    const r = spawnSync("lsblk", ["-J", "-o", "NAME,SIZE,TYPE,MOUNTPOINT,RM,ROTA,TRAN,MODEL"], { encoding: "utf8" });
    if (r.status !== 0) return { ok: false, platform: "linux", error: r.stderr || "lsblk failed" };
    try {
      const parsed = JSON.parse(r.stdout);
      return { ok: true, platform: "linux", devices: parsed.blockdevices };
    } catch (e: any) {
      return { ok: false, platform: "linux", error: e.message, raw: r.stdout };
    }
  }
  return { ok: false, platform: process.platform, error: "unsupported platform" };
}

export function generateSshKeypair(p: {
  comment?: string;
  passphrase?: string;
  type?: "ed25519" | "rsa" | "ecdsa";
  bits?: number;
}): { private_key: string; public_key: string; fingerprint_sha256: string; type: string } {
  const sshKeygen = spawnSync("ssh-keygen", ["-V"], { encoding: "utf8" });
  // Note: ssh-keygen actually uses -V for something else; just test its existence via which/where
  const test = spawnSync(process.platform === "win32" ? "where" : "which", ["ssh-keygen"], { encoding: "utf8" });
  if (test.status !== 0) {
    throw new Error("ssh-keygen not found on PATH. Install OpenSSH (Windows 10+ has it as an optional feature).");
  }
  const tmpDir = mkdtempSync(join(tmpdir(), "ssh-key-"));
  const keyPath = join(tmpDir, "id_new");
  const type = p.type ?? "ed25519";
  const args = ["-t", type, "-f", keyPath, "-N", p.passphrase ?? "", "-C", p.comment ?? `rpi-${Date.now()}`];
  if (type === "rsa") args.push("-b", String(p.bits ?? 4096));
  if (type === "ecdsa") args.push("-b", String(p.bits ?? 521));
  const g = spawnSync("ssh-keygen", args, { encoding: "utf8", input: "\n" });
  if (g.status !== 0) {
    try { rmSync(tmpDir, { recursive: true, force: true }); } catch {}
    throw new Error(`ssh-keygen failed: ${g.stderr || g.stdout}`);
  }
  try {
    const privateKey = readFileSync(keyPath, "utf8");
    const publicKey = readFileSync(`${keyPath}.pub`, "utf8").trim();
    const fp = spawnSync("ssh-keygen", ["-lf", `${keyPath}.pub`, "-E", "sha256"], { encoding: "utf8" });
    const fingerprint = fp.stdout.split(" ").find((t) => t.startsWith("SHA256:"))?.trim() ?? "";
    return {
      private_key: privateKey,
      public_key: publicKey,
      fingerprint_sha256: fingerprint,
      type,
    };
  } finally {
    try { rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  }
}
