#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { spawnSync } from "node:child_process";
import { writeFileSync, mkdirSync, existsSync, statSync } from "node:fs";
import { resolve, join } from "node:path";
import { z } from "zod";
import { OS_CATALOG, recommendOs } from "./os.js";
import { cloudInitYaml, dietpiTxt, dietpiWifiTxt, listBlockDevices, generateSshKeypair } from "./extras.js";

function textContent(data: unknown) {
  const text = typeof data === "string" ? data : JSON.stringify(data, null, 2);
  return { content: [{ type: "text" as const, text }] };
}

function errContent(msg: string) {
  return { content: [{ type: "text" as const, text: msg }], isError: true };
}

function wpaSupplicant(p: {
  ssid: string;
  psk?: string;
  key_mgmt?: "WPA-PSK" | "NONE";
  country: string;
  scan_ssid?: boolean;
  priority?: number;
  extra_networks?: Array<{ ssid: string; psk?: string; key_mgmt?: "WPA-PSK" | "NONE"; priority?: number }>;
}): string {
  const networks: string[] = [];
  const build = (n: { ssid: string; psk?: string; key_mgmt?: string; priority?: number; scan_ssid?: boolean }) => {
    const lines: string[] = ["network={"];
    lines.push(`    ssid="${n.ssid.replace(/"/g, '\\"')}"`);
    const km = n.key_mgmt ?? (n.psk ? "WPA-PSK" : "NONE");
    if (km === "WPA-PSK") {
      if (!n.psk) throw new Error("WPA-PSK requires psk");
      lines.push(`    psk="${n.psk.replace(/"/g, '\\"')}"`);
      lines.push(`    key_mgmt=WPA-PSK`);
    } else {
      lines.push(`    key_mgmt=NONE`);
    }
    if (n.priority !== undefined) lines.push(`    priority=${n.priority}`);
    if (n.scan_ssid) lines.push(`    scan_ssid=1`);
    lines.push("}");
    return lines.join("\n");
  };
  networks.push(build({ ...p }));
  for (const n of p.extra_networks ?? []) networks.push(build(n));
  return [
    `country=${p.country.toUpperCase()}`,
    `ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev`,
    `update_config=1`,
    "",
    ...networks,
    "",
  ].join("\n");
}

function hasOpenssl(): { path: string } | null {
  const r = spawnSync("openssl", ["version"], { encoding: "utf8" });
  if (r.status === 0) return { path: "openssl" };
  return null;
}

function opensslPasswdSha512(password: string): { hash: string } | { error: string } {
  if (!hasOpenssl()) {
    return {
      error: "openssl not found on PATH. Install openssl or pass password_hash directly. Manual command: openssl passwd -6 '<password>'",
    };
  }
  const r = spawnSync("openssl", ["passwd", "-6", "-stdin"], { input: password, encoding: "utf8" });
  if (r.status !== 0) {
    return { error: `openssl passwd failed: ${r.stderr || r.stdout}` };
  }
  const hash = r.stdout.trim();
  if (!hash.startsWith("$6$")) return { error: `unexpected openssl output: ${hash}` };
  return { hash };
}

function userconf(p: { username: string; password_hash: string }): string {
  if (!p.password_hash.startsWith("$")) {
    throw new Error("password_hash must be a crypt(3) hash like $6$..., $y$..., etc.");
  }
  if (p.username.includes(":")) throw new Error("username must not contain ':'");
  return `${p.username}:${p.password_hash}\n`;
}

function firstrunSh(p: {
  hostname?: string;
  locale?: string;
  timezone?: string;
  ssh_pubkey?: string;
  username?: string;
  commands?: string[];
}): string {
  const lines: string[] = [
    "#!/bin/bash",
    "# auto-generated by raspberry-pi-setup-mcp",
    "set -e",
    "",
  ];
  if (p.hostname) {
    lines.push(`hostnamectl set-hostname ${p.hostname}`);
    lines.push(`echo "127.0.1.1 ${p.hostname}" >> /etc/hosts`);
  }
  if (p.timezone) lines.push(`timedatectl set-timezone ${p.timezone}`);
  if (p.locale) lines.push(`localectl set-locale LANG=${p.locale}`);
  if (p.ssh_pubkey && p.username) {
    const esc = p.ssh_pubkey.replace(/"/g, '\\"');
    lines.push(`mkdir -p /home/${p.username}/.ssh`);
    lines.push(`echo "${esc}" >> /home/${p.username}/.ssh/authorized_keys`);
    lines.push(`chown -R ${p.username}:${p.username} /home/${p.username}/.ssh`);
    lines.push(`chmod 700 /home/${p.username}/.ssh`);
    lines.push(`chmod 600 /home/${p.username}/.ssh/authorized_keys`);
  }
  if (p.commands) for (const c of p.commands) lines.push(c);
  lines.push("rm -f /boot/firmware/firstrun.sh /boot/firstrun.sh");
  lines.push(`sed -i 's| systemd.run.*||g' /boot/firmware/cmdline.txt 2>/dev/null || sed -i 's| systemd.run.*||g' /boot/cmdline.txt 2>/dev/null || true`);
  lines.push("exit 0");
  return lines.join("\n") + "\n";
}

function prepareBoot(p: {
  target_dir: string;
  wifi?: { ssid: string; psk?: string; country: string };
  enable_ssh?: boolean;
  user?: { username: string; password?: string; password_hash?: string };
  hostname?: string;
  locale?: string;
  timezone?: string;
  ssh_pubkey?: string;
  firstrun_commands?: string[];
}) {
  const dir = resolve(p.target_dir);
  mkdirSync(dir, { recursive: true });
  const written: string[] = [];
  if (p.wifi) {
    const path = join(dir, "wpa_supplicant.conf");
    writeFileSync(path, wpaSupplicant({ ssid: p.wifi.ssid, psk: p.wifi.psk, country: p.wifi.country }), "utf8");
    written.push(path);
  }
  if (p.enable_ssh) {
    const path = join(dir, "ssh");
    writeFileSync(path, "", "utf8");
    written.push(path);
  }
  let hashResult: { hash?: string; error?: string } = {};
  if (p.user) {
    let hash = p.user.password_hash;
    if (!hash) {
      if (!p.user.password) throw new Error("user requires password or password_hash");
      const h = opensslPasswdSha512(p.user.password);
      if ("error" in h) {
        hashResult = { error: h.error };
      } else {
        hash = h.hash;
        hashResult = { hash };
      }
    } else {
      hashResult = { hash };
    }
    if (hash) {
      const path = join(dir, "userconf.txt");
      writeFileSync(path, userconf({ username: p.user.username, password_hash: hash }), "utf8");
      written.push(path);
    }
  }
  if (p.hostname || p.timezone || p.locale || p.ssh_pubkey || p.firstrun_commands?.length) {
    const path = join(dir, "firstrun.sh");
    writeFileSync(path, firstrunSh({
      hostname: p.hostname,
      timezone: p.timezone,
      locale: p.locale,
      ssh_pubkey: p.ssh_pubkey,
      username: p.user?.username,
      commands: p.firstrun_commands,
    }), "utf8");
    written.push(path);
  }
  return {
    target_dir: dir,
    written,
    notes: [
      "これらのファイルを SD カードの boot パーティション（Raspberry Pi OS の場合は 'bootfs' というラベル）の直下にコピーしてください。",
      "firstrun.sh を使うには、cmdline.txt の末尾に 'systemd.run=/boot/firmware/firstrun.sh systemd.run_success_action=reboot systemd.unit=kernel-command-line.target' を追加する必要があります。",
      "詳細は README の「firstrun.sh を有効化する」を参照。",
    ],
    ...(hashResult.error ? { password_warning: hashResult.error } : {}),
  };
}

function checkRequirements() {
  const checks: Record<string, any> = {};
  checks.openssl = hasOpenssl() ? { ok: true } : { ok: false, note: "password hashing needs openssl or pre-hashed password" };
  const rpi = spawnSync(process.platform === "win32" ? "where" : "which", ["rpi-imager"], { encoding: "utf8" });
  checks.rpi_imager = rpi.status === 0 ? { ok: true, path: rpi.stdout.trim().split(/\r?\n/)[0] } : { ok: false, note: "install from https://www.raspberrypi.com/software/" };
  const node = spawnSync("node", ["-v"], { encoding: "utf8" });
  checks.node = { version: node.stdout.trim() };
  checks.platform = process.platform;
  checks.arch = process.arch;
  return checks;
}

const server = new McpServer({ name: "raspberry-pi-setup", version: "0.1.0" });

server.tool(
  "rpi_setup",
  `Raspberry Pi の初期セットアップを支援する。OS 選定の相談から、ヘッドレス起動に必要なファイル (wpa_supplicant.conf / userconf.txt / ssh / firstrun.sh) の生成までを対話的にやる前提。

Actions:
- list_os: カタログ全件を返す。good_for タグ付き。
- recommend_os: use_case (日本語可) と experience (beginner/intermediate/advanced) を渡すと、スコアリングして上位 5 件を返す。
- generate_wpa_supplicant: WiFi 設定ファイル本文を生成。ssid / psk / country 必須。extra_networks で複数 SSID も。
- generate_userconf: Pi OS Bookworm 以降の userconf.txt (username:crypt_hash) を生成。password_hash が必要（password を渡せば openssl で生成、なければ手動で生成するコマンドを返す）。
- generate_firstrun: 初回起動時に実行される firstrun.sh を生成（ホスト名 / ロケール / TZ / SSH 公開鍵配置 / 追加コマンド）。
- enable_ssh_instructions: ssh ファイルの作り方・場所の説明を返す。
- prepare_boot: target_dir に wpa_supplicant.conf / userconf.txt / ssh / firstrun.sh をまとめて書き出す。SD カードの boot パーティションを直接指定する想定。
- hash_password: password を SHA-512 crypt ($6$...) に変換。openssl 依存。
- check_requirements: 環境チェック（openssl / rpi-imager / Node / platform / arch）。

運用モデル: LLM が子ども / 初学者から「何に使う？」を聞き出し、recommend_os で相談に乗り、prepare_boot で設定ファイルを一括生成、SD カードにコピーするだけ、という流れを想定。`,
  {
    action: z.enum([
      "list_os", "recommend_os",
      "generate_wpa_supplicant", "generate_userconf", "generate_firstrun",
      "enable_ssh_instructions", "prepare_boot",
      "hash_password", "check_requirements",
      "cloud_init_ubuntu", "dietpi_config",
      "list_block_devices", "generate_ssh_keypair",
    ]).describe("Action"),
    use_case: z.string().optional().describe("recommend_os: 用途 (例: 'プログラミング学習', 'web server', 'レトロゲーム')"),
    experience: z.enum(["beginner", "intermediate", "advanced"]).optional().describe("recommend_os: 経験レベル"),
    ssid: z.string().optional().describe("wpa_supplicant: WiFi SSID"),
    psk: z.string().optional().describe("wpa_supplicant: WiFi パスワード (WPA-PSK)"),
    country: z.string().optional().describe("wpa_supplicant: ISO 3166-1 alpha-2 国コード (例: 'JP', 'US')"),
    key_mgmt: z.enum(["WPA-PSK", "NONE"]).optional().describe("wpa_supplicant: 認証方式"),
    scan_ssid: z.boolean().optional().describe("wpa_supplicant: 非公開 SSID 対応"),
    extra_networks: z.array(z.object({
      ssid: z.string(), psk: z.string().optional(),
      key_mgmt: z.enum(["WPA-PSK", "NONE"]).optional(),
      priority: z.number().optional(),
    })).optional().describe("wpa_supplicant: 複数 SSID を設定"),
    username: z.string().optional().describe("userconf: username"),
    password: z.string().optional().describe("userconf/hash_password: 平文 (openssl で hash 化)"),
    password_hash: z.string().optional().describe("userconf: crypt(3) hash ($6$... / $y$...)"),
    hostname: z.string().optional().describe("firstrun/prepare_boot: hostname"),
    locale: z.string().optional().describe("firstrun/prepare_boot: locale (例: 'ja_JP.UTF-8')"),
    timezone: z.string().optional().describe("firstrun/prepare_boot: timezone (例: 'Asia/Tokyo')"),
    ssh_pubkey: z.string().optional().describe("firstrun/prepare_boot: SSH 公開鍵 (authorized_keys に追加)"),
    firstrun_commands: z.array(z.string()).optional().describe("firstrun: 追加で実行する bash コマンド列"),
    target_dir: z.string().optional().describe("prepare_boot: 書き出し先ディレクトリ (SD の boot パーティションを指定)"),
    enable_ssh: z.boolean().optional().describe("prepare_boot: 'ssh' 空ファイルを作る (SSH 有効化)"),
    wifi: z.object({
      ssid: z.string(),
      psk: z.string().optional(),
      country: z.string(),
    }).optional().describe("prepare_boot: WiFi 設定"),
    user: z.object({
      username: z.string(),
      password: z.string().optional(),
      password_hash: z.string().optional(),
      sudo_nopasswd: z.boolean().optional(),
    }).optional().describe("prepare_boot / cloud_init_ubuntu: 初期ユーザー"),
    packages: z.array(z.string()).optional().describe("cloud_init_ubuntu: apt パッケージ一覧"),
    runcmd: z.array(z.string()).optional().describe("cloud_init_ubuntu: runcmd に追加する shell 行"),
    dietpi: z.object({
      password: z.string().optional(),
      autostart: z.string().optional(),
      ssh_server: z.boolean().optional(),
      keyboard_layout: z.string().optional(),
      headless: z.boolean().optional(),
    }).optional().describe("dietpi_config: DietPi 固有オプション"),
    ssh_key_type: z.enum(["ed25519", "rsa", "ecdsa"]).optional(),
    ssh_key_bits: z.number().int().positive().optional(),
    ssh_key_passphrase: z.string().optional(),
    ssh_key_comment: z.string().optional(),
  },
  async (p) => {
    try {
      switch (p.action) {
        case "list_os":
          return textContent({ count: OS_CATALOG.length, os: OS_CATALOG });
        case "recommend_os": {
          if (!p.use_case) return errContent("recommend_os requires 'use_case'");
          const recs = recommendOs(p.use_case, p.experience ?? "beginner");
          return textContent({
            use_case: p.use_case,
            experience: p.experience ?? "beginner",
            count: recs.length,
            recommendations: recs,
          });
        }
        case "generate_wpa_supplicant": {
          if (!p.ssid || !p.country) return errContent("wpa_supplicant requires 'ssid' and 'country'");
          const content = wpaSupplicant({
            ssid: p.ssid, psk: p.psk, country: p.country,
            key_mgmt: p.key_mgmt, scan_ssid: p.scan_ssid,
            extra_networks: p.extra_networks,
          });
          return textContent({ filename: "wpa_supplicant.conf", content });
        }
        case "generate_userconf": {
          if (!p.username) return errContent("userconf requires 'username'");
          let hash = p.password_hash;
          let note: string | undefined;
          if (!hash) {
            if (!p.password) return errContent("userconf requires 'password' or 'password_hash'");
            const h = opensslPasswdSha512(p.password);
            if ("error" in h) return errContent(h.error);
            hash = h.hash;
          }
          const content = userconf({ username: p.username, password_hash: hash });
          return textContent({ filename: "userconf.txt", content, note });
        }
        case "generate_firstrun": {
          const content = firstrunSh({
            hostname: p.hostname, timezone: p.timezone, locale: p.locale,
            ssh_pubkey: p.ssh_pubkey, username: p.username,
            commands: p.firstrun_commands,
          });
          return textContent({
            filename: "firstrun.sh",
            content,
            note: "cmdline.txt の末尾にも 'systemd.run=/boot/firmware/firstrun.sh systemd.run_success_action=reboot systemd.unit=kernel-command-line.target' を追加する必要がある",
          });
        }
        case "enable_ssh_instructions":
          return textContent({
            summary: "SD カードの boot パーティション直下に 'ssh' という空ファイル（拡張子なし）を置くだけで SSH が有効化される。",
            filename: "ssh",
            content: "",
            note: "Bookworm 以降は userconf.txt でパスワード設定したユーザーが必要。古い Pi OS ならデフォルト pi:raspberry でログイン可（非推奨）。",
          });
        case "prepare_boot": {
          if (!p.target_dir) return errContent("prepare_boot requires 'target_dir'");
          return textContent(prepareBoot({
            target_dir: p.target_dir,
            wifi: p.wifi,
            enable_ssh: p.enable_ssh,
            user: p.user,
            hostname: p.hostname,
            locale: p.locale,
            timezone: p.timezone,
            ssh_pubkey: p.ssh_pubkey,
            firstrun_commands: p.firstrun_commands,
          }));
        }
        case "hash_password": {
          if (!p.password) return errContent("hash_password requires 'password'");
          const h = opensslPasswdSha512(p.password);
          if ("error" in h) return errContent(h.error);
          return textContent({ hash: h.hash, format: "SHA-512 crypt ($6$)" });
        }
        case "check_requirements":
          return textContent(checkRequirements());
        case "cloud_init_ubuntu": {
          if (!p.user) return errContent("cloud_init_ubuntu requires 'user'");
          let user = { ...p.user };
          if (!user.password_hash && user.password) {
            const h = opensslPasswdSha512(user.password);
            if ("error" in h) return errContent(h.error);
            user = { username: user.username, password_hash: h.hash, sudo_nopasswd: user.sudo_nopasswd };
          }
          const yaml = cloudInitYaml({
            hostname: p.hostname, timezone: p.timezone, locale: p.locale,
            user: user as any,
            ssh_pubkey: p.ssh_pubkey,
            wifi: p.wifi,
            packages: p.packages,
            runcmd: p.runcmd,
          });
          return textContent({ filename: "user-data", content: yaml, note: "Place as 'user-data' on the system-boot partition of Ubuntu Server Pi. Pair with empty 'meta-data' file." });
        }
        case "dietpi_config": {
          const txt = dietpiTxt({
            password: p.dietpi?.password,
            hostname: p.hostname,
            timezone: p.timezone,
            locale: p.locale,
            keyboard_layout: p.dietpi?.keyboard_layout,
            headless: p.dietpi?.headless,
            ssh_server: p.dietpi?.ssh_server,
            autostart: p.dietpi?.autostart,
            wifi: p.wifi,
          });
          const out: any = { "dietpi.txt": { content: txt } };
          if (p.wifi) {
            out["dietpi-wifi.txt"] = { content: dietpiWifiTxt({ ssid: p.wifi.ssid, psk: p.wifi.psk, key_mgmt: p.key_mgmt }) };
          }
          return textContent({
            files: out,
            note: "Place on the DietPi boot partition. If wifi is set, both dietpi.txt and dietpi-wifi.txt are generated.",
          });
        }
        case "list_block_devices":
          return textContent(listBlockDevices());
        case "generate_ssh_keypair":
          return textContent(generateSshKeypair({
            comment: p.ssh_key_comment,
            passphrase: p.ssh_key_passphrase,
            type: p.ssh_key_type,
            bits: p.ssh_key_bits,
          }));
      }
    } catch (err: any) {
      return errContent(`${err?.name ?? "Error"}: ${err?.message ?? String(err)}`);
    }
    return errContent("unreachable");
  },
);

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((err) => { console.error("Fatal:", err); process.exit(1); });
